# Generated by Django 4.2.5 on 2023-09-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_secretarioacademico_profesor_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tareas',
            new_name='Tarea',
        ),
    ]
