# Generated by Django 4.2.5 on 2023-09-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_tareas_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaSemana', models.CharField(max_length=10)),
                ('HoraInicio', models.TimeField()),
                ('HoraFin', models.TimeField()),
                ('modalidad', models.CharField(max_length=20)),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
