# Generated by Django 4.2.5 on 2023-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_horarioprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioprofesor',
            name='Disponibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
