# Generated by Django 4.2.5 on 2023-10-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_day_horario_hour_delete_horarioprofesor_horario_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='Disponibilidad',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='day',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='modalidad',
        ),
        migrations.AddField(
            model_name='horario',
            name='matriz',
            field=models.CharField(default='default_value', max_length=250),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
    ]
