# Generated by Django 4.2.5 on 2023-10-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_matriz_horario_diurno_horario_vespertino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='profesor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.profesor'),
        ),
    ]
