# Generated by Django 4.2.5 on 2023-10-05 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_matriz_horario_diurno_horario_vespertino'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
