# Generated by Django 4.2.5 on 2023-10-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_horario_profesor'),
        ('myapp', '0010_user_date_joined_alter_user_correo'),
    ]

    operations = [
    ]
