# Generated by Django 4.2.5 on 2023-10-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_merge_20231012_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='profesor',
            name='carrera',
            field=models.CharField(default='default_value', max_length=45),
        ),
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.CharField(default='default_value', max_length=45),
        ),
        migrations.AddField(
            model_name='profesor',
            name='diurno',
            field=models.CharField(default='default_value', max_length=250),
        ),
        migrations.AddField(
            model_name='profesor',
            name='jornada',
            field=models.CharField(default='default_value', max_length=45),
        ),
        migrations.AddField(
            model_name='profesor',
            name='vespertino',
            field=models.CharField(default='default_value', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
