# Generated by Django 4.2.5 on 2023-10-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_profesor_carrera_alter_profesor_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='diurno',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=250),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='vespertino',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=250),
        ),
    ]
