# Generated by Django 4.2.5 on 2023-10-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_profesor_diurno_alter_profesor_vespertino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=255)),
                ('fechaHora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('unidadAcademica', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('materia', models.CharField(max_length=255)),
                ('Curso', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=10)),
                ('jornada', models.CharField(max_length=20)),
                ('nrc', models.CharField(max_length=20)),
                ('listaCruzada', models.CharField(max_length=255)),
                ('nrcLigados', models.CharField(max_length=255)),
                ('idListaCurzada', models.IntegerField()),
                ('calificable', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('nombreAsignatura', models.CharField(max_length=255)),
                ('horasAPagar', models.IntegerField()),
                ('tipoActividad', models.CharField(max_length=255)),
                ('modalidad', models.CharField(max_length=20)),
                ('numeroVacantes', models.IntegerField()),
                ('numeroInscritos', models.IntegerField()),
                ('restriccionCodPrograma', models.CharField(max_length=255)),
                ('restriccionDescPrograma', models.CharField(max_length=255)),
                ('restriccionCampus', models.CharField(max_length=255)),
                ('nivelCurso', models.IntegerField()),
                ('unidadQuePaga', models.CharField(max_length=255)),
                ('semestreQuePaga', models.CharField(max_length=20)),
                ('prorcentajeOnline', models.FloatField()),
                ('proveedor', models.CharField(max_length=255)),
                ('administrador', models.CharField(max_length=255)),
                ('iniciativa', models.CharField(max_length=255)),
                ('aulas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('jornada', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='diurno',
            new_name='horarioDiurno',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='vespertino',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clave',
        ),
        migrations.AddField(
            model_name='profesor',
            name='horarioVespertino',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=250),
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.CharField(max_length=255)),
                ('horaFin', models.CharField(max_length=255)),
                ('dia', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='planificacionAcademica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.planificacionacademica'),
        ),
    ]
