# Generated by Django 4.2.5 on 2023-10-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auditoria_curso_planificacionacademica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fechaHora',
            field=models.CharField(max_length=255),
        ),
    ]
